name: Build and Deploy Jekyll Site

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: false

      - name: Install system dependencies
        run: |
          sudo apt-get install -y build-essential zlib1g-dev liblzma-dev imagemagick
          pip install jupyter nbconvert

      - name: Install bundler
        run: gem install bundler

      - name: Bundle install (clean)
        run: bundle install --full-index

      - name: Build site
        run: bundle exec jekyll build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy
        uses: actions/deploy-pages@v4
